# include the path to the camera2world matrix

preprocessing:
  input_data_dir: "/home/jacinto/robot-grasp/data/rgbd_videos_tax3d/"
  output_data_dir: "/home/jacinto/robot-grasp/data/tax3d/"
  technique: "final_frame_and_se3_transform"
  object_name: "mug."
  num_objects: 1
  camera2world_file: "/home/jacinto/robot-grasp/data/camera_calibration/camera2robot.npz"
  world_frame: True
  debug: True

# Dataset options
sample_size_action: 512
sample_size_anchor: 512
downsample_type: fps
world_frame: True

train_size: null
val_size: null

# Dataset data augmentation options
center_type: anchor_center # [action_center, anchor_center, anchor_random, none], centers the point clouds w.r.t. the action, anchor, or no centering
action_context_center_type: center # [center, random, none], centers the action context point clouds
# pcd_scale_factor: 15.0 # Scale factor for the point clouds
action_transform_type: identity # Transformation type to apply to demonstrations
anchor_transform_type: random_flat_upright # Transformation type to apply to demonstrations
translation_variance: 0.0 # Translation variance of the demo transformation
rotation_variance: 180 # Rotation variance of the demo transformation
